[package]
name = "loop-device"
description = "Canopus native class schedule app (Loop)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
default = []
device = ["dep:canopus-target-private"]
target-xiaomi-band-10-pro-3-101-036 = ["device", "canopus-target-private/target-xiaomi-band-10-pro-3-101-036"]
target-xiaomi-band-10-pro-3-101-043 = ["device", "canopus-target-private/target-xiaomi-band-10-pro-3-101-043"]

[dependencies]
loop-core = { path = "../loop-core", default-features = false }
canopus-abi = { path = "../../../Canopus/sdk/rust/canopus-abi" }
canopus-runtime = { path = "../../../Canopus/sdk/rust/canopus-runtime" }
canopus-ui-core = { path = "../../../Canopus/sdk/rust/canopus-ui-core" }
canopus-target-private = { path = "../../../Canopus/sdk/rust/canopus-target-private", optional = true, default-features = false }
