#!/usr/bin/env python3
"""Encode verifier-ambiguous constant words and emit pre-Rust fixups."""

import argparse
import json
import pathlib
import re
import struct

HIT = re.compile(
    r"ERROR: embedded absolute address (?P<section>\S+)\+0x(?P<offset>[0-9a-fA-F]+) "
    r"(?P<value>0x[0-9a-fA-F]+) not in target pack allowlist"
)
MASK = 0xA5A5A5A5
# The fixup array is padded to a fixed width so its size (and therefore the
# relocatable-link section layout that determines which string bytes alias a
# firmware address) is stable between the layout pass and the final link.
# Without this, the two-pass pipeline oscillates between N and N-1 hits.
MAX_FIXUPS = 16
ANCHORS = {
    ".rodata": "canopus_rodata_anchor",
    ".rodata.str1.1": "canopus_rodata_str1_1_anchor",
    ".rodata.cst8": "canopus_rodata_cst8_anchor",
}


def parse_hits(text: str) -> list[dict[str, int | str]]:
    hits = []
    errors = []
    for line in text.splitlines():
        if "ERROR:" not in line:
            continue
        if "undefined symbol 'canopus_decode_opaque_words'" in line:
            continue
        match = HIT.search(line)
        if match is None:
            errors.append(line.strip())
            continue
        section = match.group("section")
        if section not in ANCHORS:
            errors.append(f"unsupported opaque-word section: {section}")
            continue
        value = int(match.group("value"), 16)
        encoded = value ^ MASK
        if 0x0C000000 <= encoded < 0x0C500000:
            errors.append(f"encoded word still aliases firmware: 0x{encoded:08x}")
            continue
        hits.append({
            "section": section,
            "offset": int(match.group("offset"), 16),
            "value": value,
            "mask": MASK,
        })
    if errors:
        raise SystemExit("\n".join(errors))
    unique = {(hit["section"], hit["offset"]): hit for hit in hits}
    return [unique[key] for key in sorted(unique)]


def generate(args: argparse.Namespace) -> None:
    hits = parse_hits(pathlib.Path(args.verifier_output).read_text())
    if not hits:
        raise SystemExit("verifier reported no opaque constant words")
    if len(hits) > MAX_FIXUPS:
        raise SystemExit(
            f"too many opaque words ({len(hits)} > {MAX_FIXUPS}); "
            "raise MAX_FIXUPS in encode-opaque-words.py"
        )
    lines = [
        "/* Generated by encode-opaque-words.py; do not edit. */",
        "#include <stdint.h>",
        "",
    ]
    for anchor in sorted({ANCHORS[str(hit["section"])] for hit in hits}):
        lines.append(f"extern const uint8_t {anchor}[];")
    lines.extend([
        "",
        "struct canopus_opaque_fixup {",
        "    volatile uint32_t *word;",
        "    uint32_t mask;",
        "};",
        "",
        "__attribute__((section(\".data.canopus_fixups\"), used))",
        "static struct canopus_opaque_fixup canopus_opaque_fixups[] = {",
    ])
    for index in range(MAX_FIXUPS):
        if index < len(hits):
            hit = hits[index]
            anchor = ANCHORS[str(hit["section"])]
            lines.append(
                f"    {{(volatile uint32_t *)({anchor} + 0x{int(hit['offset']):x}), "
                f"0x{int(hit['mask']):08x}u}},"
            )
        else:
            lines.append("    {0, 0},")
    lines.extend([
        "};",
        "",
        "void canopus_decode_opaque_words(void)",
        "{",
        "    unsigned int i;",
        "    for (i = 0; i < (unsigned int)(sizeof(canopus_opaque_fixups) /",
        "                                    sizeof(canopus_opaque_fixups[0])); ++i) {",
        "        if (canopus_opaque_fixups[i].word != 0",
        "            && canopus_opaque_fixups[i].mask != 0) {",
        "            *canopus_opaque_fixups[i].word ^= canopus_opaque_fixups[i].mask;",
        "        }",
        "    }",
        "}",
        "",
    ])
    pathlib.Path(args.output_c).write_text("\n".join(lines))
    pathlib.Path(args.metadata).write_text(json.dumps(hits, indent=2) + "\n")
    print(f"generated {len(hits)} opaque-word fixups")


def elf_sections(data: bytearray) -> dict[str, tuple[int, int]]:
    if data[:4] != b"\x7fELF" or data[4] != 1 or data[5] != 1:
        raise SystemExit("expected ELF32 little-endian input")
    shoff = struct.unpack_from("<I", data, 32)[0]
    shentsize, shnum, shstrndx = struct.unpack_from("<HHH", data, 46)
    if shentsize < 40 or shstrndx >= shnum:
        raise SystemExit("invalid ELF section table")
    shstr = shoff + shstrndx * shentsize
    strings_offset, strings_size = struct.unpack_from("<II", data, shstr + 16)
    strings = data[strings_offset:strings_offset + strings_size]
    sections = {}
    for index in range(shnum):
        header = shoff + index * shentsize
        name_offset = struct.unpack_from("<I", data, header)[0]
        end = strings.find(0, name_offset)
        if end < 0:
            raise SystemExit("unterminated ELF section name")
        name = bytes(strings[name_offset:end]).decode("ascii", "strict")
        file_offset, size = struct.unpack_from("<II", data, header + 16)
        sections[name] = (file_offset, size)
    return sections


def patch(args: argparse.Namespace) -> None:
    path = pathlib.Path(args.elf)
    data = bytearray(path.read_bytes())
    sections = elf_sections(data)
    hits = json.loads(pathlib.Path(args.metadata).read_text())
    for hit in hits:
        section = str(hit["section"])
        offset = int(hit["offset"])
        value = int(hit["value"])
        mask = int(hit["mask"])
        if section not in sections:
            raise SystemExit(f"missing ELF section: {section}")
        file_offset, size = sections[section]
        if offset + 4 > size:
            raise SystemExit(f"fixup outside {section}: 0x{offset:x}")
        current = struct.unpack_from("<I", data, file_offset + offset)[0]
        if current != value:
            raise SystemExit(
                f"constant moved at {section}+0x{offset:x}: "
                f"expected 0x{value:08x}, found 0x{current:08x}"
            )
        struct.pack_into("<I", data, file_offset + offset, value ^ mask)
    path.write_bytes(data)
    print(f"encoded {len(hits)} opaque words in {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest="command", required=True)
    generate_parser = commands.add_parser("generate")
    generate_parser.add_argument("--verifier-output", required=True)
    generate_parser.add_argument("--output-c", required=True)
    generate_parser.add_argument("--metadata", required=True)
    generate_parser.set_defaults(run=generate)
    patch_parser = commands.add_parser("patch")
    patch_parser.add_argument("--elf", required=True)
    patch_parser.add_argument("--metadata", required=True)
    patch_parser.set_defaults(run=patch)
    args = parser.parse_args()
    args.run(args)


if __name__ == "__main__":
    main()
