-- Generated by Canopus/scripts/build_module_installer_prod.py.
-- Generated module installer; CPC2/CMI1 flow shared with BluetoothAudio prod.
local CONFIG = {["token"] = "loop",
["title"] = "Loop",
["max_size"] = 393216,
["stem"] = "loop",
["assets"] = {"appicon_loop.bin"},
["targets"] = {["3.101.036"] = {["id"] = "xiaomi-band-10-pro-3.101.036",
["firmware"] = "662d67f5e247e31e194d3161024890ba93b9d29d70b290fadb9aac8ce8ec3c81",
["runtime_pending"] = false,
["build"] = "CONBINE_LTALM078_T3.101.036_06242053"},
["3.101.043"] = {["id"] = "xiaomi-band-10-pro-3.101.043",
["firmware"] = "519307675665e4866d722a8119a98589c397b614ac3294cb87bfc86de45756ec",
["runtime_pending"] = false,
["build"] = "CONBINE_LTALM078_T3.101.043_08041658"}}}
local progress = (function()
-- One checkpoint per UI timer tick. Never busy-wait or call timer:ready():
-- the event loop must get a chance to paint before the next operation.
local M = {}
function M.new(lvgl, changed, finished)
    local timer, task
    local active = false
    local function stop()
        active = false
        if timer then
            local old = timer
            timer = nil
            old:delete()
        end
        task = nil
    end
    local function advance()
        if not active then return end
        local ok, result = coroutine.resume(task)
        if not ok then
            stop()
            finished(false, tostring(result))
        elseif coroutine.status(task) == "dead" then
            stop()
            finished(true, result)
        else
            changed(result)
        end
    end
    return {
        start = function(work)
            if active then return false, "An operation is already running" end
            if type(lvgl.Timer) ~= "function" then return false, "LuaLVGL Timer unavailable" end
            task = coroutine.create(work)
            local ok, created = pcall(lvgl.Timer, {
                period = 120, repeat_count = -1, paused = true,
                cb = function()
                    local tick_ok, message = pcall(advance)
                    if not tick_ok then stop(); finished(false, tostring(message)) end
                end,
            })
            if not ok or not created then task = nil; return false, tostring(created) end
            timer, active = created, true
            local started, message = pcall(function()
                advance() -- first resume only publishes the first checkpoint
                if timer then timer:resume() end
            end)
            if not started then stop(); return false, tostring(message) end
            return true
        end,
        checkpoint = function(text) coroutine.yield(text) end,
        cancel = function()
            local old = task
            stop()
            if old and coroutine.status(old) == "suspended" then coroutine.close(old) end
        end,
    }
end
return M

end)()
local lvgl = require("lvgl")
local function read_all(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local ok, data = pcall(f.read, f, "*a")
    local closed, result = pcall(f.close, f)
    if not ok or not closed or not result then return nil end
    return data
end
local function u16(data, off) return string.unpack("<I2", data, off + 1) end
local function u32(data, off) return string.unpack("<I4", data, off + 1) end
-- Device family: ENDPOINT, REPLY_SIZE, SUPERVISOR_MISSING, BUILD_PROPERTY,
-- fallback_identity(), prepare_inbox(checkpoint), failure_detail(response, exchange).
-- Band 10 Pro Lua keeps os.execute and /dev access, so this keeps the
-- device-proven flow of the earlier installers: /dev/canopus (registered by
-- every Supervisor, including those without the ordinary-IO installer node),
-- a 36-byte reply and a CPS1 status query for the diagnostic. Its build.prop
-- carries ro.build.id without the build date; the exact build string is
-- ro.build.customer_version.
local ENDPOINT, REPLY_SIZE = "/dev/canopus", 36
local SUPERVISOR_MISSING = "请先运行 Canopus 框架安装表盘"
local BUILD_PROPERTY = "ro.build.customer_version"
local execute = os.execute
local function getprop(key)
    local temp = "/data/" .. CONFIG.token .. "-installer-prop.tmp"
    local ok = execute("getprop " .. key .. " > " .. temp)
    local value = (ok == true or ok == 0) and read_all(temp)
    if type(os.remove) == "function" then pcall(os.remove, temp) end
    value = type(value) == "string" and value:match("^%s*(.-)%s*$")
    return value ~= "" and value or nil
end
local function fallback_identity()
    -- The framework installer identifies this firmware through getprop.
    if type(execute) ~= "function" then return nil end
    return getprop("ro.build.version"), getprop(BUILD_PROPERTY)
end
local function prepare_inbox(checkpoint)
    if type(execute) ~= "function" then return end
    checkpoint("准备模块安装目录")
    -- mkdir may report EEXIST; the staged writes determine usability.
    execute("mkdir /data/canopus")
    execute("mkdir /data/canopus/inbox")
end
local function failure_detail(_, exchange)
    local ok, record = pcall(exchange,
        string.pack("<I4I4I4I4", 0x43504331, 0x43510001, 0x43514431, 0), 384)
    if not ok or u32(record, 0) ~= 0x43505331 then return "" end
    return " error " .. string.unpack("<i4", record, 33)
end
local properties = {}
local identity = read_all("/etc/build.prop")
local identity_invalid = false
if identity then
    for line in (identity .. "\n"):gmatch("([^\n]*)\n") do
        local k, v = line:gsub("\r$", ""):match("^([^=]+)=(.*)$")
        if k then
            if properties[k] ~= nil then identity_invalid = true end
            properties[k] = v
        end
    end
end
local version = not identity_invalid and properties["ro.build.version"]
local build = properties[BUILD_PROPERTY]
if not identity then version, build = fallback_identity() end
local target = version and CONFIG.targets[version]
local startup_error
if not target or (target.build and build ~= target.build) then
    startup_error = "不支持的固件：" .. tostring(version or "Unknown")
end

local width, height = lvgl.HOR_RES(), lvgl.VER_RES()
local rootbase = lvgl.Object(nil, {
    w = width, h = height, bg_color = 0x07111F,
    bg_opa = lvgl.OPA(100), border_width = 0,
})
local root = lvgl.Object(rootbase, {
    w = width, h = height, bg_color = 0x07111F, bg_opa = lvgl.OPA(100),
    border_width = 0, pad_all = 0, align = lvgl.ALIGN.CENTER,
})
rootbase:clear_flag(lvgl.FLAG.SCROLLABLE)
root:clear_flag(lvgl.FLAG.SCROLLABLE)
lvgl.Label(root, {
    text = CONFIG.title, text_color = 0xFFFFFF,
    text_font = lvgl.Font("MiSans-Regular", width < 300 and 18 or 24),
    w = width - 32, h = 48,
    align = { type = lvgl.ALIGN.TOP_MID, x_ofs = 0, y_ofs = 52 },
})
local status = lvgl.Label(root, {
    text = "准备安装...", text_color = 0xBFD9FF,
    text_font = lvgl.Font("MiSans-Regular", width < 300 and 14 or 18),
    w = width - 32, h = height - 146,
    align = { type = lvgl.ALIGN.TOP_MID, x_ofs = 0, y_ofs = 106 },
})
local function fail(message)
    status:set { text = "安装失败\n" .. tostring(message), text_color = 0xFF9A9A }
end
if startup_error then fail(startup_error); return end

local runner, current
local function checkpoint(text) runner.checkpoint(text) end
local function check(ok, message) if not ok then error(message, 0) end end
local function fixed(data, off, size) return data:sub(off + 1, off + size):match("^[^%z]*") end
local function hex(data) return (data:gsub(".", function(c) return string.format("%02x", c:byte()) end)) end
local function write_file(path, data)
    local f = io.open(path, "wb")
    check(f, "无法打开：" .. path)
    local ok, result = pcall(f.write, f, data)
    local closed, close_result = pcall(f.close, f)
    check(ok and result and (type(result) ~= "number" or result == #data)
        and closed and close_result, "写入失败：" .. path)
end
local function device_exchange(request, size)
    -- Request and result must remain synchronous: Supervisor shares a mailbox.
    local f = io.open(ENDPOINT, "wb")
    check(f, SUPERVISOR_MISSING)
    local ok, result, message = pcall(f.write, f, request)
    local closed, close_result = pcall(f.close, f)
    check(ok and result and (type(result) ~= "number" or result == #request)
        and closed and close_result, message or "Supervisor write failed")
    f = io.open(ENDPOINT, "rb")
    check(f, "Cannot read supervisor response")
    local read_ok, response = pcall(f.read, f, size)
    closed, close_result = pcall(f.close, f)
    check(read_ok and type(response) == "string" and #response == size
        and closed and close_result, "Invalid supervisor response")
    return response
end
local function install()
    checkpoint("检查 Canopus 运行环境")
    local f = io.open(ENDPOINT, "rb")
    check(f, SUPERVISOR_MISSING)
    f:close()
    checkpoint("读取目标模块与签名")
    local stem = SCRIPT_PATH .. CONFIG.stem .. "-" .. target.id
    local receipt, module = read_all(stem .. ".cmi.bin"), read_all(stem .. ".bin")
    checkpoint("校验固件、模块和签名配对")
    check(type(receipt) == "string" and #receipt == 256
        and u32(receipt, 0) == 0x31494D43 and u32(receipt, 4) == 1
        and u32(receipt, 8) == 256 and fixed(receipt, 32, 32) == CONFIG.token
        and fixed(receipt, 64, 48) == target.id
        and hex(receipt:sub(113, 144)) == target.firmware,
        "Missing or invalid target receipt")
    check(type(module) == "string" and #module >= 512 and #module <= CONFIG.max_size
        and module:sub(1, 7) == "\127ELF\1\1\1"
        and u16(module, 16) == 1 and u16(module, 18) == 40,
        "Missing or invalid relocatable ARM module")
    check(u32(receipt, 24) == #module, "Receipt artifact size mismatch")
    local assets = {}
    for _, name in ipairs(CONFIG.assets) do
        checkpoint("校验图标：" .. name)
        local data = read_all(SCRIPT_PATH .. name)
        check(type(data) == "string" and #data >= 12 and data:sub(1, 4) == "\25\16\0\0"
            and u16(data, 4) > 0 and u16(data, 6) > 0
            and u16(data, 8) == u16(data, 4) * 4 and u16(data, 10) == 0
            and #data == 12 + u16(data, 6) * u16(data, 8), "Invalid icon: " .. name)
        assets[#assets + 1] = {name, data}
    end
    prepare_inbox(checkpoint)
    local payloads = {
        {"inbox/" .. CONFIG.token .. ".cmi", receipt},
        {"inbox/" .. CONFIG.token .. ".ko", module},
    }
    for _, asset in ipairs(assets) do payloads[#payloads + 1] = asset end
    for _, item in ipairs(payloads) do
        local path = "/data/canopus/" .. item[1]
        checkpoint("写入：" .. item[1])
        write_file(path, item[2])
        checkpoint("回读校验：" .. item[1])
        check(read_all(path) == item[2], "Staged file verification failed")
    end
    checkpoint("提交签名验证与安装请求")
    local payload = CONFIG.token .. "\0"
    local request = string.pack("<I4I2I2I2I2I4I4I4I4I4I4",
        0x43504332, 36, 1, 1, 0, 36 + #payload, 2, 1, 0, 0, #payload) .. payload
    local response = device_exchange(request, REPLY_SIZE)
    check(u32(response, 0) == 0x43504332 and u16(response, 4) == 36
        and u16(response, 6) == 2 and u16(response, 8) == 1
        and u32(response, 12) == REPLY_SIZE and u32(response, 16) == 2
        and u32(response, 20) == 1 and u32(response, 24) == 0
        and u32(response, 32) == REPLY_SIZE - 36, "Invalid supervisor response")
    if u32(response, 28) ~= 5 then
        local detail = "Supervisor result " .. u32(response, 28)
            .. failure_detail(response, device_exchange)
        error(detail, 0)
    end
    return target.runtime_pending and
        "安装完成，模块保持禁用。\n\n本固件的音频运行适配尚未完成。\n\n可在管理器查看安装记录。" or
        "安装完成，默认禁用。\n\n请在 Canopus 管理器中查看和启用模块。"
end
local sequence = 0
runner = progress.new(lvgl, function(text)
    current, sequence = text, sequence + 1
    status:set {text = "步骤 " .. sequence .. "\n" .. text, text_color = 0xBFD9FF}
end, function(ok, message)
    if ok then status:set {text = message, text_color = 0x8FF0A4}
    else fail(tostring(current) .. "\n" .. tostring(message)) end
end)
if lvgl.EVENT.DELETE then rootbase:onevent(lvgl.EVENT.DELETE, function() runner.cancel() end) end
local ok, message = runner.start(install)
if not ok then fail(message) end
